### ISSUE TITLE
Smoke Test CI/CD Integration 

### ISSUE THREAD

**Issue by BorisYourich** [CESNET/tesp-api#17]
**Is your feature request related to a problem? Please describe.**
Currently there is no automated test suite for Push or PR validation.

**Describe the solution you'd like**
- [x] Create/Curate tests in the `tests` directory for general Smoke Test validation of basic and critical functions of the **tesp-api**
- [x] Rename `tests/test_src.py` to `tests/smoke_tests.py` for better readability of code.
- [x] Add job to `.github/workflows/ci.yaml` CI pipline  which will run `pytest tests/smoke_tests.py` on push and PR.

Might be useful: https://naodeng.medium.com/pytest-tutorial-advance-usage-integration-ci-cd-and-github-action-c627c7cbbc22

**Describe alternatives you've considered**
NA

**Additional context**
This is part of a larger set of CI testing features necessary to implement in the project

**Comment by micoleaoo** [comment]
Closed by #19 solved all tasks.
